### ISSUE TITLE
The model weight of headhunter?

### ISSUE THREAD

**Issue by PlumedSerpent** [Sentient07/HeadHunter--T#1]
Where can I download the pretrained model weight of headhunter?

**Comment by Sentient07** [comment]
Hello, here is the weight : https://drive.google.com/file/d/1CODnsMrFrOCsE7XL9jBDP42GUz3rbUwH/view?usp=sharing

The reproducible config file has been uploaded. Now you can reproduce the table 12 (and related ones) of the paper. Hope that helps
