### ISSUE TITLE
Have you released the pre-training model yet

### ISSUE THREAD

**Issue by neversettle-tech** [Sentient07/HeadHunter--T#10]
Have you published the pre-training model and we would like to test it on our data set to see how it works

**Comment by Sentient07** [comment]
https://github.com/Sentient07/HeadHunter--T#note-

**Comment by Sentient07** [comment]
https://drive.google.com/file/d/1CODnsMrFrOCsE7XL9jBDP42GUz3rbUwH/view?usp=sharing
