### ISSUE TITLE
cuda 10.0 or cuda 11.1?

### ISSUE THREAD

**Issue by eplatero97** [Sentient07/HeadHunter--T#4]
Hello, on the `Setup Instructions` section of the README.md file, it is stated that "Cuda 10.0 is needed if Docker is unavailable."

However, when I looked at line 45 of the `env_super.yml` file, I find that a torch version with cuda 11.1 is installed (`torch==1.8.1+cu111`).

As such, is cuda 10.0 or cuda 11.1 the requirement to run the model? Or is there something else that I'm not noticing?

Best regards,
Erick Platero

**Comment by Sentient07** [comment]
Hello, sorry for this ambiguity. As mentioned in [this comment](https://github.com/Sentient07/HeadHunter/issues/2#issuecomment-881879855) the env file isn't the exact one I used for this project. I don't work at the same lab anymore and don't have access to the previous working environment. So I just uploaded on github, my current working environment, where I managed to test and reproduce the results (for tracking and detection on our benchmark). I haven't myself tried to train using this environment. IIRC, the pytorch version I use was 1.6 and Cuda version was 10.0. I hope that helps

**Comment by eplatero97** [comment]
Oh, okay. So, to make it clear, you are saying that you were able to test and reproduce the results for tracking and detection using the `env_super.yml` environment. However, I am assuming you reproduced these results using the pre-trained weights you mentioned [here](https://github.com/Sentient07/HeadHunter--T/issues/1). In that case, you have not trained the model from scratch using the `env_super.yml` file, correct?

**Comment by Sentient07** [comment]
Yep, that's a good summary.

**Comment by eplatero97** [comment]
Okay, thank you so much for the clarification.

In short then, cuda 10.0 was the original version used to run the model. However, since the original dependencies of the model are currently unavailable, cuda 11.1 was used when re-creating the benchmarks of the model using the pre-trained weights mentioned [here](https://github.com/Sentient07/HeadHunter--T/issues/1).

I will now be closing this issue :+1:
