### ISSUE TITLE
the link of pretrained model is unvalid 

### ISSUE THREAD

**Issue by taohan10200** [Sentient07/HeadHunter--T#5]
this [link](https://drive.google.com/file/d/1CODnsMrFrOCsE7XL9jBDP42GUz3rbUwH/view?usp=sharing) is not available now,  could you mind sharing the latest link to help me get `FT_R50_epoch_24.pth` ?

**Comment by Sentient07** [comment]
![image](https://user-images.githubusercontent.com/6195312/142449209-2d5daeff-c774-437d-b725-5e9462417232.png)
It does work for me?
