### ISSUE TITLE
run_mot.py wrong to work

### ISSUE THREAD

**Issue by ReverseSacle** [Sentient07/HeadHunter--T#7]
![1636372048(1)](https://user-images.githubusercontent.com/73418195/140736809-5c1d14a0-9084-4275-9051-1dda7b59e6d9.png)
Hi,
There is something wrong when i try to use``` run_mot.py``` to predict The MOT20's test datasets.
I have already set some parameters in ```run_mot.py``` file(Just like --base-dir,--save-path and --dataset),but it just look like something missing when I run this file.

**Comment by Sentient07** [comment]
Hello, this repository is for head detection and MOT20 benchmark AFAIK is a full-body detection dataset. Could that be the reason why it doesn't work?
