### ISSUE TITLE
Same Tracker ID-But in alternate frames

### ISSUE THREAD

**Issue by akirs82** [Sentient07/HeadHunter--T#8]
Hello there,

When i tried to run on a custoam dataset,am seeing the tracker ids are maintained in alternate frames for many people. For example if person1 has tracker ID 1 in frame1,ID 2 in frame2 then the ids are maintained for frame3,frame4,frame5,frame6 as ID1,ID2,ID1,ID2,ID1,ID2. This is weird,is it because of the nms ? Also all my head detections score are 1 when i am supplying to tracker.

**Comment by Sentient07** [comment]
Hello,

I don't have access to your custom dataset and I cannot help you here unfortunately. Also, this repository is dedicated to our paper and we do not help with customized adaptations. sorry about that.
