### ISSUE TITLE
Cannot figure out how to use the estimate module in particlefilter.py

### ISSUE THREAD

**Issue by yx98314** [Sentient07/HeadHunter--T#9]
In your article you said that Given the new location and importanceweight of each particle, estimated position of kth track is
computed as weighted mean of the particles.
But in the code of the HeadhunterT,the estimate module had no usages in all places
![1638846025(1)](https://user-images.githubusercontent.com/67858482/144958296-16325f94-d8a6-45ae-9367-b6b8e97587b9.png)

**Comment by Sentient07** [comment]
https://github.com/Sentient07/HeadHunter--T/blob/21be0dd912c09af76b5387af19fc30fc18f17bc1/particleFilter.py#L102-L108
